kind: ConfigMap
apiVersion: v1
metadata:
  name: nginx-keda-example
  namespace: default
data:
  default.conf: |
    server {
        listen 80;
        server_name example.com;

        location / {
          root /usr/share/nginx/html;
          index index.html;
        }

        location /metrics {
          stub_status;
          allow all;
        }
    }
