# reference: https://keda.sh/docs/2.10/concepts/scaling-deployments/
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: nginx-keda-example
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: nginx-keda-example
    envSourceContainerName: nginx
  minReplicaCount: 1
  maxReplicaCount: 5
  triggers:
  - type: prometheus
    metadata:
      serverAddress: http://operator-kube-prometheus-s-prometheus.default.svc:9090
      metricName: 'nginx_http_requests_total'
      threshold: '50'
      query: sum(http_requests_total)
