apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-custom-metric
  namespace: default
spec:
  selector:
    matchLabels:
      app: nginx-custom-metric
  template:
    metadata:
      labels:
        app: nginx-custom-metric
    spec:
      containers:
      - name: nginx
        image: nginx
        resources:
          limits:
            memory: "64Mi"
            cpu: "100m"
        ports:
        - containerPort: 80
        volumeMounts:
        - name: nginx-config-volume
          mountPath: /etc/nginx/conf.d
      # reference: https://github.com/nginxinc/nginx-prometheus-exporter
      - name: exporter
        image: nginx/nginx-prometheus-exporter:0.11
        args:
        - '-nginx.scrape-uri=http://localhost/metrics'
        resources:
          limits:
            memory: "64Mi"
            cpu: "100m"
        ports:
        - containerPort: 9113
      volumes:
      - name: nginx-config-volume
        configMap:
          name: nginx-custom-metrics
