apiVersion: v1
kind: Service
metadata:
  name: nginx-custom-metric
  namespace: default
  labels:
    app: nginx-custom-metric
spec:
  type: NodePort
  selector:
    app: nginx-custom-metric
  ports:
  - name: nginx
    protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30951
  - name: exporter
    protocol: TCP
    port: 9113
    targetPort: 9113
    nodePort: 30952
